---
name: Workflow Test
on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS distro'
        required: true
        type: string
    secrets:
      MY_SECRET:
        description: 'Secret to expose to the job'
        required: true
      GAR_USER:
        description: 'Google Artifact Registry user'
        required: true
      GAR_PASS:
        description: 'Google Artifact Registry password'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: theberbat/robotnik-ros:${{ inputs.ros_distro }}-builder
      credentials:
        username: ${{ secrets.GAR_USER }}
        password: ${{ secrets.GAR_PASS }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/package
      - run: find .
      - run: ls /opt
      - run: find /opt
