---
name: Workflow Test
on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS distro'
        required: true
        type: string
    secrets:
      GAR_USER:
        description: 'Google Artifact Registry user'
        required: true
      GAR_PASS:
        description: 'Google Artifact Registry password'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: theberbat/robotnik-ros:${{ inputs.ros_distro }}-builder
      credentials:
        username: ${{ secrets.GAR_USER }}
        password: ${{ secrets.GAR_PASS }}
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ros_distro }}
          path: src/package
      - name: Update dependencies
        run: |
          apt-get update
          local_deps.sh
      - name: Download and install dependencies
        run: |
          rosdep install --from-paths src --ignore-src -r -y
      - name: Build
        run: |
          source /opt/ros/${{ inputs.ros_distro }}/setup.bash
          catkin config --install
          catkin build
      - name: Generate packages
        run: |
          source /opt/ros/${{ inputs.ros_distro }}/setup.bash
          source ./install/local_setup.bash
          generate_debs.sh
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: debs
          retention-days: 1
