---
name: Workflow Test
on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS distro'
        required: true
        type: string
    secrets:
      MY_SECRET:
        description: 'Secret to expose to the job'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
      - run: echo "The event name is ${{ github.event_name }}"
      - run: echo "Custom secret ${{ secrets.MY_SECRET }}"
      - run: echo "Custom input ${{ inputs.ros_distro }}"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
